output: weights/tokenizer.json
vocab_size: 64000

total_chars: 1000000000
streaming: true

data:
    - { preset: tinystories, weight: 1 }
    - { preset: wikipedia-en, weight: 1 }
    - { preset: cosmopedia, weight: 1 }
