"""Turn HuggingFace text datasets into a common iterator of strings.

Both tokenizer training (scripts/train_tokenizer.py) and preprocessing
(scripts/preprocess.py) need to stream text from a dataset one item at a time,
so that logic is centralized here.

With streaming=True even huge datasets download shards lazily, so combining it
with `limit` lets you do a quick sanity check on just the first N items.
"""

from dataclasses import dataclass, field
from typing import Callable, Iterator

from datasets import load_dataset


@dataclass
class DatasetSpec:
    path: str  # HF Hub repo id, e.g. "roneneldan/TinyStories"
    name: str | None = None  # config / subset name, e.g. "20231101.en"
    split: str = "train"
    text_key: str = "text"  # column that holds the text
    # Use this to format several columns into one text (e.g. GSM8K question + answer).
    format: Callable[[dict], str] | None = field(default=None, repr=False)

    def to_text(self, row: dict) -> str:
        if self.format is not None:
            return self.format(row)
        return row[self.text_key]


# Presets for commonly used datasets, referenced via --preset.
PRESETS: dict[str, DatasetSpec] = {
    # --- Sanity checks (smallest first) ---
    "wikitext": DatasetSpec("Salesforce/wikitext", "wikitext-2-raw-v1"),  # ~4MB
    # --- Easy / early curriculum: simple vocabulary, basic content ---
    # Synthetic children's stories with a tiny vocabulary (kindergarten level).
    "tinystories": DatasetSpec("roneneldan/TinyStories"),  # ~2GB
    # Children's stories, a bit richer than TinyStories but still simple.
    "children-stories": DatasetSpec(
        "ajibawa-2023/Children-Stories-Collection"
    ),
    # Grade-school math word problems (question + worked answer).
    "gsm8k": DatasetSpec(
        "openai/gsm8k",
        "main",
        format=lambda r: f"{r['question']}\n{r['answer']}",
    ),
    # --- Educational / textbook (Phi-style: high pedagogical value) ---
    # Synthetic textbooks/blogposts/stories generated by Mixtral (Phi-inspired).
    "cosmopedia": DatasetSpec("HuggingFaceTB/cosmopedia", "web_samples_v2"),
    # 420k synthetic "textbook" documents, inspired by phi-1.5.
    "tiny-textbooks": DatasetSpec("nampdn-ai/tiny-textbooks", text_key="textbook"),
    # 147k synthetic textbooks ordered simple -> complex (curriculum-structured).
    "tiny-orca-textbooks": DatasetSpec(
        "nampdn-ai/tiny-orca-textbooks", text_key="textbook"
    ),
    # "Textbooks Are All You Need"-style long-form textbooks (markdown body).
    "textbooks": DatasetSpec("open-phi/textbooks", text_key="markdown"),
    # Web pages filtered for educational value, scored toward grade/middle-school
    # knowledge (English / Japanese). Closest open analogue to Phi's filtering.
    "fineweb-edu": DatasetSpec("HuggingFaceFW/fineweb-edu", "sample-10BT"),
    "fineweb-edu-ja": DatasetSpec(
        "hotchpotch/fineweb-2-edu-japanese", "sample_10BT"
    ),
    # --- General knowledge / broad web (hardest, most diverse) ---
    "wikipedia-en": DatasetSpec("wikimedia/wikipedia", "20231101.en"),
    "wikipedia-ja": DatasetSpec("wikimedia/wikipedia", "20231101.ja"),
    "fineweb-ja": DatasetSpec("HuggingFaceFW/fineweb-2", "jpn_Jpan"),
}


@dataclass
class Mixture:
    """A corpus that mixes several sources by a character-count budget.

    BPE is frequency-based, so ordering does not matter. `weights` allocates the
    number of characters read from each source, which effectively determines how
    much of the vocabulary each language gets (byte balancing).
    """

    specs: list[DatasetSpec]
    weights: list[float]


# Recipes for tokenizer training. Balance Japanese and English to roughly 50:50
# by character count.
RECIPES: dict[str, Mixture] = {
    "ja-en": Mixture(
        specs=[
            PRESETS["wikipedia-ja"],
            PRESETS["fineweb-ja"],
            PRESETS["wikipedia-en"],
            PRESETS["cosmopedia"],
        ],
        weights=[0.25, 0.25, 0.25, 0.25],  # JP 0.5 / EN 0.5
    ),
}


def iter_texts(
    spec: DatasetSpec,
    streaming: bool = True,
    limit: int | None = None,
    max_chars: int | None = None,
) -> Iterator[str]:
    """Yield non-empty texts one at a time from the dataset described by `spec`.

    When max_chars is set, stop once the cumulative character count reaches it
    (used for byte balancing).
    """
    ds = load_dataset(spec.path, spec.name, split=spec.split, streaming=streaming)
    if limit is not None:
        ds = ds.take(limit) if streaming else ds.select(range(min(limit, len(ds))))
    n_chars = 0
    for row in ds:
        text = spec.to_text(row)
        if text and text.strip():
            yield text
            if max_chars is not None:
                n_chars += len(text)
                if n_chars >= max_chars:
                    return


def iter_mixture(
    mix: Mixture,
    total_chars: int,
    streaming: bool = True,
) -> Iterator[str]:
    """Read each source of the Mixture up to its weighted character budget and
    concatenate them."""
    for spec, w in zip(mix.specs, mix.weights):
        yield from iter_texts(
            spec, streaming=streaming, max_chars=int(total_chars * w)
        )


def resolve_spec(preset: str | None, dataset: str | None) -> DatasetSpec:
    """Resolve a DatasetSpec from CLI arguments.

    Either --preset <name> or --dataset "path[:name[:split[:text_key]]]".
    """
    if preset is not None:
        if preset not in PRESETS:
            raise SystemExit(
                f"unknown preset '{preset}'. choices: {', '.join(PRESETS)}"
            )
        return PRESETS[preset]
    if dataset is not None:
        path, *rest = dataset.split(":")
        name = rest[0] if len(rest) > 0 and rest[0] else None
        split = rest[1] if len(rest) > 1 and rest[1] else "train"
        text_key = rest[2] if len(rest) > 2 and rest[2] else "text"
        return DatasetSpec(path, name, split, text_key)
    raise SystemExit("either --preset or --dataset is required")
